---
title: "FRC Tournment Orga Guideline"
format: html
editor: visual
---

# TWO WEEKS BEFORE

-   Send a reminder for signing in our Women\*'s WhatsApp for people to sign up on SpielerPlus (both for players and for support)

-   Once you know how many players are coming, ask Fiona if she booked a bus.

# ONE WEEK BEFORE

### Create a tournment WhatsApp group

-   add the players who confirmed in SpielerPlus and send a link in the main woman group

### Send a prompt message in tournament group

Complete the prompt message below with all the information and send in the tournament group:

> We are driving to \[CITY\] for our next tournament on \[DATE\]. For this we stuff: who has the 3 balls? Who has the bottle box? Who has the Trikots? Who has the medi bag? Who prints the player list? Who can bring/buy a pack magnesium electrolytes (paid with the Teamkasse)

(FYI) Game day items and where they live:

-   Balls: someone has to take them from training

-   Bottle box: take from the hut

-   Trikots: usually at somebody's place; ask them to bring it

-   Medi bag: also usually at somebody’s place but ask if anything needs to be replaced)

-   Player List: Print the PDF and bring along

###   Organize the social:

-   Choose a location and estimate a meeting time

    -   Prefer Oscar Wilde's and O'Keely's because they are our sponsors

    -   Oscar Wilde's takes reservation, O'Kelly's does not

-   Advertise the social in the Women\*'s WhatsApp group

-   Keep both the tournament and the Women\*'s WhatsApp group informed of any last minute changes in meeting point or meeting time

### Decide on a meeting time

-   Once the captains/coaches announce the tournament schedule (2-3 days before):

    -   ask captains about long we need for warm-up, hair, taping do you plan enough time

    -   plan a buffer of 30 minutes for traffic

    -   meeting time should be 15 minutes before we leave

# DAY BEFORE

-    Remind everyone to pack Mundschutz, Hosen, Stollenschuhe, food, their own tape if needed

-   Announce meeting time in the tournament WhatsApp group

# AFTER THE TOURNMENT

-    Make a mental note on who took the trikots home to give them a bath

-   Takes notes if anything is missing in the Medi-box
